<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>BITWebVersioning</AssemblyName>
    <RootNamespace>BITWebVersioning</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\Shared\ReleaseVersion.cs" Link="ReleaseVersion.cs" />
  </ItemGroup>
</Project>
